name: MLOps-CI

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: data processing
      run: |
        python src/data/run_processing.py \
        --input data/raw/house_data.csv \
        --output data/processed/cleaned_house_data.csv
    - name: feature engineering
      run: |
        python src/features/engineer.py \
          --input data/processed/cleaned_house_data.csv \
          --output data/processed/featured_house_data.csv \
          --preprocessor models/trained/preprocessor.pkl
    - name: setup and start mlflow server
      run: |
       docker pull ghcr.io/mlflow/mlflow:latest 
       docker run -idt --name mlflow -p 5000:5000 \
        ghcr.io/mlflow/mlflow:latest \
        mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 
    - name: model training
      run: |
        
        python src/models/train.py \
          --input data/processed/featured_house_data.csv \
          --model_output models/trained/house_price_model.pkl \
          --preprocessor_output models/trained/preprocessor.pkl \
          --mlflow_tracking_uri http://localhost:5000 \
    - name: model evaluation
      run: |
        python src/models/evaluate.py \
          --input data/processed/featured_house_data.csv \
          --model_input models/trained/house_price_model.pkl \
          --preprocessor_input models/trained/preprocessor.pkl \
          --mlflow_tracking_uri http://localhost:5000 \
          --mlflow_experiment_name house_price_prediction
    - name: Stop and remove mlflow container
      run: |
        docker stop mlflow
        docker rm mlflow       