name: MLOps Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  data-processing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process data
        run: |
          python src/data/run_processing.py   \
          --input data/raw/house_data.csv   \
          --output data/processed/cleaned_house_data.csv
    #   - name: Process data
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: cleaned house data  
    #       path: data/processed/cleaned_house_data.csv
      - name: Engineer features
        run: |
          python src/features/engineer.py   \
          --input data/processed/cleaned_house_data.csv   \
          --output data/processed/featured_house_data.csv   \
          --preprocessor models/trained/preprocessor.pkl
      - name: Upload processed data
        uses: actions/upload-artifact@v4        
        with:
          name: processed-data
          path: data/processed/featured_house_data.csv
      - name: Upload preprocessor
        uses: actions/upload-artifact@v4        
        with:
          name: model trained
          path: models/trained/preprocessor.pkl
  model-training:
    runs-on: ubuntu-latest
    needs: data-processing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download processed data
        uses: actions/download-artifact@v5
        with:
          name: processed-data
          path: data/processed/
      - name: Set MLFlow tracking URI
        run: |
            docker pull sanjaygeeky/mlflow:latest
            docker run -d -p 5000:5000 --name mlflow sanjaygeeky/mlflow:latest mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./tmp/mlruns 
            export MLFLOW_TRACKING_URI=http://localhost:5000
      - name: Wait for MLflow to start
        run:
            for i in {1..10}; do
            curl -f http://localhost:5000/health || sleep 5;
            done
      - name: Train model
        run: |
          python src/models/train_model.py   \
          --config configs/model_config.yaml   \
          --data data/processed/featured_house_data.csv   \
          --models-dir models   \
          --mlflow-tracking-uri http://localhost:5000  
      - name:  Upload trained model
        uses: actions/upload-artifact@v4        
        with:
          name: trained-model
          path: models/ 
      - name: Clean up MLflow
        run: |
                docker stop mlflow || true
                docker rm mlflow || true
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    needs: model-training

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download model trained artifact
        uses: actions/download-artifact@v5
        with:
          name: trained-model  
          path: models/
      - name: preprocessor
        uses: actions/download-artifact@v4
        with:
            name: preprocessor
            path: models/trained/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          #DOCKERHUB_USERNAME
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            #DOCKERHUB_TOKEN

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .Dockerfile
          push: true
          tags: |
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:latest